
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hammad Ashraf
 */
public class RELATIONS extends javax.swing.JFrame {
DBConn obj=new DBConn();
  int xx;
int xy;  /**
     * Creates new form RELATIONS
     */
    public RELATIONS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtgroom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtbride = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtstatus = new javax.swing.JTextField();
        btninsert = new javax.swing.JButton();
        btndlt = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        txtupdate = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        TABLE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Record = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GROOM");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BRIDE");

        txtbride.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtbridePropertyChange(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATE");

        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("STATUS");

        btninsert.setBackground(new java.awt.Color(255, 255, 255));
        btninsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btninsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insert_32px.png"))); // NOI18N
        btninsert.setBorderPainted(false);
        btninsert.setContentAreaFilled(false);
        btninsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btninsert.setDefaultCapable(false);
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });

        btndlt.setBackground(new java.awt.Color(255, 255, 255));
        btndlt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_32px.png"))); // NOI18N
        btndlt.setBorderPainted(false);
        btndlt.setContentAreaFilled(false);
        btndlt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndltActionPerformed(evt);
            }
        });

        btnsearch.setBackground(new java.awt.Color(255, 255, 255));
        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_32px.png"))); // NOI18N
        btnsearch.setBorderPainted(false);
        btnsearch.setContentAreaFilled(false);
        btnsearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(255, 255, 255));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/broom_32px.png"))); // NOI18N
        btnclear.setBorderPainted(false);
        btnclear.setContentAreaFilled(false);
        btnclear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclear.setDefaultCapable(false);
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        txtupdate.setBackground(new java.awt.Color(255, 255, 255));
        txtupdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update_tag_32px.png"))); // NOI18N
        txtupdate.setBorderPainted(false);
        txtupdate.setContentAreaFilled(false);
        txtupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtupdate.setDefaultCapable(false);
        txtupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtupdateActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(0, 102, 102));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angle_left_32px.png"))); // NOI18N
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.setFocusPainted(false);
        jToggleButton1.setFocusable(false);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel6.setText("RELATIONS");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_32px.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setDefaultCapable(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TABLE.setBackground(new java.awt.Color(255, 255, 255));
        TABLE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TABLE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/visible_32px.png"))); // NOI18N
        TABLE.setBorderPainted(false);
        TABLE.setContentAreaFilled(false);
        TABLE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TABLE.setDefaultCapable(false);
        TABLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TABLEActionPerformed(evt);
            }
        });

        Record.setBackground(new java.awt.Color(0, 204, 204));
        Record.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "GROOM", "BRIDE", "DATE", "STATUS"
            }
        ));
        Record.setGridColor(new java.awt.Color(255, 255, 255));
        Record.setSelectionBackground(new java.awt.Color(0, 204, 204));
        jScrollPane1.setViewportView(Record);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtgroom, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btninsert)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtupdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnsearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndlt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnclear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TABLE)))
                        .addGap(371, 371, 371)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(txtdate, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(txtbride)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(txtid)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstatus))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jToggleButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtgroom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtbride, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btninsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btndlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnclear))
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TABLE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
   String id=txtid.getText();
   String groom=txtgroom.getText();
   String bride=txtbride.getText();
   String date=txtdate.getText();
   String status=txtstatus.getText();
         String query ="INSERT INTO RELATIONS (REL_ID ,REL_GROOM ,REL_BRIDE ,REL_DATE ,REL_STATUS) VALUES  ('"+id+"','"+groom+"','"+bride+"','"+date+"','"+status+"')";
        DBConn obj=new DBConn();
        boolean b=obj.UDI(query);
  if(b==true)
  {
      JOptionPane.showMessageDialog(null,"Inserted");
  }
  else
  {
        JOptionPane.showMessageDialog(null,"Not Inserted");
  }      txtid.requestFocusInWindow();      // TODO add your handling code here:1
    }//GEN-LAST:event_btninsertActionPerformed

    private void btndltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndltActionPerformed
        String id=txtid.getText();
   String groom=txtgroom.getText();
   String bride=txtbride.getText();
   String date=txtdate.getText();
   String status=txtstatus.getText();
         String query ="DELETE from RELATIONS where REL_ID='"+id+"'";
        DBConn obj=new DBConn();
        boolean b=obj.UDI(query);
  if(b==true)
  {
      JOptionPane.showMessageDialog(null,"DELETED");
  }
  else
  {
        JOptionPane.showMessageDialog(null,"Not DELETED");
        
  }   
txtid.requestFocusInWindow();// TODO add your handling code here:
    }//GEN-LAST:event_btndltActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
 String iD=txtid.getText();
        
     


    String query ="Select*FROM RELATIONS where REL_ID='"+iD+"'";
         ResultSet rs=obj.Search(query);
            try{ 
 
            
           if(rs.next())
           {
               txtgroom.setText(rs.getString("REL_GROOM"));
              txtbride.setText(rs.getString("REL_BRIDE"));
              txtdate.setText(rs.getString("REL_DATE"));
               txtstatus.setText(rs.getString("REL_STATUS"));
           }
           else{
                JOptionPane.showMessageDialog(null,"SEARCH not FOUND");
           }
           
            JOptionPane.showMessageDialog(null,"SERCHED SUCESSFULLY");
        } 
        catch(Exception ex)
        {
             JOptionPane.showMessageDialog(null,"Exception Occured"+ex.getMessage());
        }   
  txtid.requestFocusInWindow();        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void txtupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtupdateActionPerformed
 
        String id=txtid.getText();
   String groom=txtgroom.getText();
   String bride=txtbride.getText();
   String date=txtdate.getText();
   String status=txtstatus.getText();


    String query ="Update RELATIONS SET REL_GROOM='"+groom+"',REL_BRIDE='"+bride+"',REL_DATE='"+date+"',REL_STATUS='"+status+"' where REL_ID='"+id+"'";  
    
        DBConn obj=new DBConn();
        boolean b=obj.UDI(query);
  if(b==true)
  {
      JOptionPane.showMessageDialog(null,"updated");
  }
  else
  {
        JOptionPane.showMessageDialog(null,"Not updated");
  }    txtid.requestFocusInWindow();        // TODO add your handling code here:
    }//GEN-LAST:event_txtupdateActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
txtid.setText("");
txtgroom.setText("");
txtbride.setText("");
txtdate.setText("");
txtstatus.setText("");
txtid.requestFocusInWindow();   


        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
HAMMAD obj8=new HAMMAD();    
    obj8.setVisible(true);
        this.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
int x=evt.getXOnScreen();
int y=evt.getYOnScreen();
this.setLocation(x-xx,y-xy);         // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
xx=evt.getX();
xy=evt.getY();
setOpacity((float)0.7);         // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
setOpacity((float)1.0);        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TABLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TABLEActionPerformed
        String query ="Select* from RELATIONS";

        try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");

            Connection conn = DriverManager.getConnection("jdbc:ucanaccess://D:\\MBB\\MarriageBeurro.accdb");
            conn.createStatement();
            Statement stmt2 = conn.createStatement();
            stmt2.execute(query);
            ResultSet rs=stmt2.getResultSet();
            int rI=0;
            while(rs.next()){
                Record.getModel().setValueAt(rs.getString("REL_ID"), rI, 0);
                Record.getModel().setValueAt(rs.getString("REL_GROOM"), rI, 1);
                Record.getModel().setValueAt(rs.getString("REL_BRIDE"), rI, 2);
                Record.getModel().setValueAt(rs.getString("REL_DATE"), rI, 3);
                Record.getModel().setValueAt(rs.getString("REL_STATUS"), rI, 4);

            }

            conn.close();
        }
        catch(java.lang.ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null,"Exception Occured is "+ex.getMessage());

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Exception Occured "+ex.getMessage());

        }
    }//GEN-LAST:event_TABLEActionPerformed

    private void txtbridePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtbridePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbridePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RELATIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RELATIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RELATIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RELATIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RELATIONS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Record;
    private javax.swing.JButton TABLE;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndlt;
    private javax.swing.JButton btninsert;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txtbride;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtgroom;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtstatus;
    private javax.swing.JButton txtupdate;
    // End of variables declaration//GEN-END:variables
}
